from jinja2 import Template


def generate_markdown_report(title, content):

    template = Template("""
# {{ title }}

## Generated Report

{{ content }}

---

Generated by Autonomous Research Agent
""")

    return template.render(
        title=title,
        content=content
    )


def generate_html_report(title, content):

    template = Template("""
<html>
<head>
    <title>{{ title }}</title>
</head>

<body>

<h1>{{ title }}</h1>

<h2>Generated Report</h2>

<p>{{ content }}</p>

<hr>

<p>Generated by Autonomous Research Agent</p>

</body>
</html>
""")

    return template.render(
        title=title,
        content=content
    )


def generate_code_snippet(language, task):

    return f"""
# Auto-generated {language} code

# Task:
# {task}

def solution():

    print("Generated solution placeholder")
"""


def canvas_tool(
    output_type,
    title,
    content,
    language=None
):

    if output_type == "markdown":

        return generate_markdown_report(
            title,
            content
        )

    elif output_type == "html":

        return generate_html_report(
            title,
            content
        )

    elif output_type == "code":

        return generate_code_snippet(
            language,
            content
        )

    return "Unsupported output type"