from jinja2 import Template
from vertexai.generative_models import GenerativeModel
from pydantic import BaseModel, Field
from typing import Literal

class CanvasRequest(BaseModel):
    output_type: Literal["markdown", "html", "code"] = Field(..., description="The format of the output.")
    title: str = Field(..., description="The title of the document or report.")
    content: str = Field(..., description="The main content or task description.")
    language: str = Field("python", description="The programming language for code snippets.")

async def canvas_tool(
    output_type: str,
    title: str,
    content: str,
    language: str = "python"
) -> str:
    """Generates complex outputs like Markdown reports, HTML documents, or REAL code snippets.
    
    Args:
        output_type: The format of the output ('markdown', 'html', or 'code').
        title: The title of the document or report.
        content: The main content or task description for the tool.
        language: The programming language for code snippets (default: 'python').
    """
    # Validation using Pydantic
    try:
        CanvasRequest(output_type=output_type, title=title, content=content, language=language)
    except Exception as e:
        return f"Validation Error: {str(e)}"

    if output_type == "markdown":
        template = Template("# {{ title }}\n\n## Generated Report\n\n{{ content }}\n\n---\nGenerated by Autonomous Research Agent")
        return template.render(title=title, content=content)

    elif output_type == "html":
        template = Template("<html><head><title>{{ title }}</title></head><body><h1>{{ title }}</h1><h2>Generated Report</h2><p>{{ content }}</p><hr><p>Generated by Autonomous Research Agent</p></body></html>")
        return template.render(title=title, content=content)

    elif output_type == "code":
        # Phase 6 Requirement: Real code generation
        model = GenerativeModel("gemini-2.0-flash")
        prompt = f"""
        You are an expert software engineer.
        Generate a professional {language} code snippet for the following task:
        
        Task: {content}
        
        Provide ONLY the code, no markdown backticks or explanations.
        """
        response = model.generate_content(prompt)
        return response.text

    return "Unsupported output type"
