from jinja2 import Template

async def canvas_tool(
    output_type: str,
    title: str,
    content: str,
    language: str = "python"
) -> str:
    """Generates complex outputs like Markdown reports, HTML documents, or code snippets.
    
    Args:
        output_type: The format of the output ('markdown', 'html', or 'code').
        title: The title of the document or report.
        content: The main content or task description for the code.
        language: The programming language for code snippets (default: 'python').
    """
    if output_type == "markdown":
        template = Template("# {{ title }}\n\n## Generated Report\n\n{{ content }}\n\n---\nGenerated by Autonomous Research Agent")
        return template.render(title=title, content=content)

    elif output_type == "html":
        template = Template("<html><head><title>{{ title }}</title></head><body><h1>{{ title }}</h1><h2>Generated Report</h2><p>{{ content }}</p><hr><p>Generated by Autonomous Research Agent</p></body></html>")
        return template.render(title=title, content=content)

    elif output_type == "code":
        return f"# Auto-generated {language} code\n# Task: {content}\n\ndef solution():\n    print('Generated solution placeholder')\n"

    return "Unsupported output type"
